nombre= input("-Escriba su nombre: ")
apellido = input("-Escriba su apellido: ")
correo = input("-Escriba su correo: ")
edad = int(input("-Escriba su edad: "))
altura = int(input("-Escriba su altura: "))
print("//")
print('->Su nombre es: ',nombre)
print('->Su apellido es: ',apellido)
print('->Su correo es: ',correo)
print('->Su edad es: ',edad)
print('->Su altura es: ',altura)